In [12]:
import numpy as np
import scipy as sp
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn import preprocessing

In [13]:
input_data = np.array([[5.1, -2.9, 3.3,], [-1.2, 7.8, -6.1], [3.9, 0.4, 2.1], [7.3, -9.9, -4.5]])

### Бинаризация

In [14]:
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
data_binarized

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

### Исключение среднего
#### До

In [15]:
print("Mean", input_data.mean(axis=0))
print("Std devitation", input_data.std(axis=0))

Mean [ 3.775 -1.15  -1.3  ]
Std devitation [3.12039661 6.36651396 4.0620192 ]


#### После

In [17]:
data_scaled = preprocessing.scale(input_data)
print("Mean", data_scaled.mean(axis=0))
print("Std devitation", data_scaled.std(axis=0))

Mean [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std devitation [1. 1. 1.]


### Масштабирование

In [19]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin Max scaled data\n")
data_scaled_minmax


Min Max scaled data



array([[0.74117647, 0.39548023, 1.        ],
       [0.        , 1.        , 0.        ],
       [0.6       , 0.5819209 , 0.87234043],
       [1.        , 0.        , 0.17021277]])

### Нормализация данных

In [20]:
data_normalized_l1 = preprocessing.normalize(input_data, norm="l1")
data_normalized_l2 = preprocessing.normalize(input_data, norm="l2")

In [24]:
print("L1 normalized data")
data_normalized_l1

L1 normalized data


array([[ 0.45132743, -0.25663717,  0.2920354 ],
       [-0.0794702 ,  0.51655629, -0.40397351],
       [ 0.609375  ,  0.0625    ,  0.328125  ],
       [ 0.33640553, -0.4562212 , -0.20737327]])

In [25]:
print("L2 normalized data")
data_normalized_l2

L2 normalized data


array([[ 0.75765788, -0.43082507,  0.49024922],
       [-0.12030718,  0.78199664, -0.61156148],
       [ 0.87690281,  0.08993875,  0.47217844],
       [ 0.55734935, -0.75585734, -0.34357152]])

## Кодирование меток